---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# shellcheck disable=all

# NTP Time Sync Configuration
ntp:
  enabled: true
  ntp_client: systemd-timesyncd
  servers:
    - time.google.com

growpart:
  mode: auto
  devices: ['/']
  ignore_growroot_disabled: false

resize_rootfs: true

# Cloud-config file to start the k3s cluster.
runcmd:
  - |
    # Allow helm/kubectl access from external development system
    iptables -A INPUT -p tcp --dport 6443 -j ACCEPT
    . /etc/environment

