---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Security scan on tag

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
permissions:
  contents: read

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@7d14e6a6f6b86c1a5dcb4c6c59b8767f821ec690
    with:
      run_build: false
      run_version_tag: false
      run_repo_pipeline: false
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
      NO_AUTH_ECR_PUSH_USERNAME: ${{ secrets.NO_AUTH_ECR_PUSH_USERNAME }}
      NO_AUTH_ECR_PUSH_PASSWD: ${{ secrets.NO_AUTH_ECR_PUSH_PASSWD }}
      MSTEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
